### ISSUE TITLE
Use Styled Components best practices

### ISSUE THREAD

**Issue by peduarte** [kitze/twizzy-landing#13]
I'm surprised [this PR](https://github.com/kitze/twizzy-landing/pull/5) has actually been merged. 

There are loads of tweets encouraging people to take a look at this codebase for learning reasons. Some people may focus on React only (Hooks, Suspense, etc) but some people may also learn other things, such as styling.

I can see how this PR was more of a troll from @mxstbr but if it's been decided to be merged, I think it'd only be fair to your audience to use styled components best practices.

For example:

Correct import
```diff
- import emotion from 'styled-components`
+ import styled from 'styled-components`
```

Prefer template literal (as encouraged by SC docs)
```diff
- export const ProgressRing = emotion.svg({
-   position: 'relative',
-   transform: 'rotate(-90deg)'
- });
+ export const ProgressRing = styled.svg`
+   position: relative;
+   transform: rotate(-90deg);
+ `;
```

**Comment by mxstbr** [comment]
> Correct import

Yep this should definitely be fixed.

> Prefer template literal (as encouraged by SC docs)

We don't prefer template literals anymore, see https://www.styled-components.com/docs/advanced#style-objects!

**Comment by peduarte** [comment]
@mxstbr Oh yeah of course, if @kitze prefers style objects that's absolutely up to him, all I meant is that template literal seems to be encouraged by Styled Components, hence a "best practice". At least that's the feeling I get from the docs and [this article you wrote](https://www.smashingmagazine.com/2017/01/styled-components-enforcing-best-practices-component-based-systems/#enforcing-best-practices)

But on a second thought, you're right, I don't know why that *would be* a best practice, it just seems more common :)

**Comment by kitze** [comment]
Max changed `emotion` to `styled` but objects vs template literals is a personal preference, not a best practice. Objects are way easier to work with, and they were the #1 reason why I wasn't using styled-components in my projects.
