### ISSUE TITLE
`react-app-rewired start

### ISSUE THREAD

**Issue by zydeico** [kitze/twizzy-landing#25]
How i can fix this, i can´t start the app with **npm start**
This is the log file result
**20 error code ELIFECYCLE
21 error errno 1
22 error twizzy-landing@1.0.0 start: `react-app-rewired start`
22 error Exit status 1
23 error Failed at the twizzy-landing@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]**

**Comment by kitze** [comment]
It looks like some problem with npm. Have you tried with yarn?

**Comment by zydeico** [comment]
It never crossed my mind to try it with yarn, it was solved 😀
